### PR TITLE
bug 683312 remove footer links from unified branch

### PR DESCRIPTION
**Pull request by chrismore**
Removed footer right, logo, and footer links from the unified branch.

### CODE REVIEW

**Comment by chrismore** [comment]
@Osmose here is one for the unified branch. r?

**Comment by Osmose** [comment]
The patch itself looks fine, but I don't think it's worth bothering to make this change to Affiliates. I tried to get some numbers on how many people were leaving the site through those links, but I couldn't find anything useful. Having said that, I suspect that the amount of traffic Affiliates gets (240k pageviews in the past month) and the amount of time they spend on the page on average (about 2 seconds) is due to people hitting the page and closing it quickly; generally users wouldn't be able to get through the list of links at the top or bottom in 2 seconds.

If you really think this needs to change before the redesign lands I can merge this and see about making the change to Affiliates, but I'd prefer to just wait. :D

**Comment by chrismore** [comment]
This bug came about after a conversation with product marketing about the /mobile page on mozilla.org and footer links on Affiliates. I then mentioned the footer from Affiliates and AMO/Nightly are similar, but is separate code. The decision was to get these changes done between now and MWC at the end of February, which will still be before we get to the Affiliates 2.0.

**Comment by Osmose** [comment]
r+ then. :D

**Pull request merged**
